backend:
  name: github
  repo: teqsun/mkdoc-wiki-ADN
  branch: main
  site_domain: teqsun.github.io

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
